name: dotnet build & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore PinballApi.slnx
      - name: Build
        run: dotnet build PinballApi.slnx --configuration Release --no-restore
      - name: Configure WPPR Secret
        run: dotnet user-secrets set "WPPRKey" ${{secrets.WPPRKEY}} --project PinballApi.Tests/PinballApi.Tests.csproj
      - name: Configure OPDB Secret
        run: dotnet user-secrets set "OPDBToken" ${{secrets.OPDBTOKEN}} --project PinballApi.Tests/PinballApi.Tests.csproj
      - name: Configure MatchPlayApi Secret
        run: dotnet user-secrets set "MatchPlayApiToken" "${{secrets.MATCHPLAYAPITOKEN}}" --project PinballApi.Tests/PinballApi.Tests.csproj
      - name: Test
        run: dotnet test PinballApi.slnx --configuration Release --no-build --logger trx --results-directory "TestResults"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results
          path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
