name: publish to nuget
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"  
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push PinballApi.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_TOKEN}}
        env:
          GITHUB_TOKEN: ${{secrets.NUGET_TOKEN}}
